import 'package:flutter/material.dart';

// ignore: camel_case_types
class items {
  Icon icon;
  String title;
  String dec;
  items({required this.icon, required this.title, required this.dec});
}

List<items> data = [
  items(
      icon: const Icon(Icons.settings),
      title: "Definition",
      dec:
          "<p><strong>Definition of English Grammar:</strong>&nbsp;English grammar is the way in which meanings are encoded into wordings in the English language.</p> <p>&nbsp; &nbsp; &nbsp;This includes the structure of words, phrases, clauses, and sentences, right up to the structure of whole texts.</p> <p><strong>What is Lorem Ipsum?</strong></p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p> <p><strong><img alt=\"To see images, Turn on internet Connection\" src=\"https://drive.google.com/uc?id=1cZIrXFPEjCcz3LQvih3leXF2nENg0uSd\" style=\"width: 100%; height: 250px;\" /></strong></p> <p><strong>Where does it come from?</strong></p> <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>"),
  items(
      icon: const Icon(Icons.no_accounts),
      title: "Letter and Word",
      dec:
          "<p><strong>Definition of Letter:</strong>&nbsp;English grammar is the way in which meanings are encoded into wordings in the English language.</p> <p>&nbsp; &nbsp; &nbsp;This includes the structure of words, phrases, clauses, and sentences, right up to the structure of whole texts.</p> <p><strong>What is Lorem Ipsum?</strong></p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p> <p><strong><img alt=\"To see images, Turn on internet Connection\" src=\"https://drive.google.com/uc?id=1KU6fem5Qvk-LYaCePsXz8ZnfZsxedtBn\" style=\"width: 100%; height: 250px;\" /></strong></p> <p><strong>Where does it come from?</strong></p> <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>"),
  items(
      icon: const Icon(Icons.notifications_off),
      title: "Number",
      dec:
          "<p><strong>Definition of Number:</strong> English grammar is the way in which meanings are encoded into wordings in the English language.</p> <p>&nbsp; &nbsp; &nbsp;This includes the structure of words, phrases, clauses, and sentences, right up to the structure of whole texts.</p>"),
  items(
      icon: const Icon(Icons.add),
      title: "Gender",
      dec:
          "<p><strong>Definition of Gender:</strong> A symbol or character that is conventionally used in writing and printing to represent a speech sound and that is part of an alphabet is called letter.</p> <p>&nbsp;</p> <p><strong>Definition of Word:</strong> A single distinct meaningful element of speech or writing, used with others (or sometimes alone) to form a sentence and typically shown with a space on either side when written or printed is called a word.</p>"),
  items(
      icon: const Icon(Icons.remove),
      title: "Person",
      dec:
          "<p><strong>Definition of Person:</strong>&nbsp;English grammar is the way in which meanings are encoded into wordings in the English language.</p> <p>&nbsp; &nbsp; &nbsp;This includes the structure of words, phrases, clauses, and sentences, right up to the structure of whole texts.</p> <p><strong>What is Lorem Ipsum?</strong></p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p> <p><strong><img alt=\"To see images, Turn on internet Connection\" src=\"https://drive.google.com/uc?id=1cZIrXFPEjCcz3LQvih3leXF2nENg0uSd\" style=\"width: 100%; height: 250px;\" /></strong></p> <p><strong>Where does it come from?</strong></p> <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>"),
  items(
      icon: const Icon(Icons.notifications_on),
      title: "Case",
      dec:
          "<p><strong>Definition of Case:</strong>&nbsp;English grammar is the way in which meanings are encoded into wordings in the English language.</p> <p>&nbsp; &nbsp; &nbsp;This includes the structure of words, phrases, clauses, and sentences, right up to the structure of whole texts.</p> <p><strong>What is Lorem Ipsum?</strong></p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p> <p><strong><img alt=\"To see images, Turn on internet Connection\" src=\"https://drive.google.com/uc?id=1cZIrXFPEjCcz3LQvih3leXF2nENg0uSd\" style=\"width: 100%; height: 250px;\" /></strong></p> <p><strong>Where does it come from?</strong></p> <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>"),
  items(
      icon: const Icon(Icons.person),
      title: "Assertive Sentence",
      dec:
          "<p><strong>Definition of Sentense:</strong>&nbsp;English grammar is the way in which meanings are encoded into wordings in the English language.</p> <p>&nbsp; &nbsp; &nbsp;This includes the structure of words, phrases, clauses, and sentences, right up to the structure of whole texts.</p> <p><strong>What is Lorem Ipsum?</strong></p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p> <p><strong><img alt=\"To see images, Turn on internet Connection\" src=\"https://drive.google.com/uc?id=1lOyoy7UduLpyKzC9m1iMAuKyYgq5bC6E\" style=\"width: 100%; height: 250px;\" /></strong></p> <p><strong>Where does it come from?</strong></p> <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>"),
  items(
      icon: const Icon(Icons.food_bank),
      title: "Imperative ",
      dec:
          "<p><strong>Interrogative Sentence:</strong>&nbsp;English grammar is the way in which meanings are encoded into wordings in the English language.</p> <p>&nbsp; &nbsp; &nbsp;This includes the structure of words, phrases, clauses, and sentences, right up to the structure of whole texts.</p> <p><strong>What is Lorem Ipsum?</strong></p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p> <p><strong><img alt=\"To see images, Turn on internet Connection\" src=\"https://drive.google.com/uc?id=1cZIrXFPEjCcz3LQvih3leXF2nENg0uSd\" style=\"width: 100%; height: 250px;\" /></strong></p> <p><strong>Where does it come from?</strong></p> <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>"),
  items(
      icon: const Icon(Icons.access_alarm),
      title: "Optative Sentence",
      dec:
          "<p><strong>Optative Sentence:</strong> Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p> <p>&nbsp; &nbsp; &nbsp;Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p> <p>&nbsp; &nbsp; &nbsp;It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."),
  items(
      icon: const Icon(Icons.lock),
      title: "Exclamatory Sentence",
      dec:
          "<p><strong>Exclamatory Sentence:</strong>&nbsp;English grammar is the way in which meanings are encoded into wordings in the English language.</p> <p>&nbsp; &nbsp; &nbsp;This includes the structure of words, phrases, clauses, and sentences, right up to the structure of whole texts.</p> <p><strong>What is Lorem Ipsum?</strong></p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p> <p><strong><img alt=\"To see images, Turn on internet Connection\" src=\"https://drive.google.com/uc?id=1cZIrXFPEjCcz3LQvih3leXF2nENg0uSd\" style=\"width: 100%; height: 250px;\" /></strong></p> <p><strong>Where does it come from?</strong></p> <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>"),
  items(
      icon: const Icon(Icons.ac_unit),
      title: "Noun",
      dec:
          "<p><strong>Definition of Noun:</strong> Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p> <p>&nbsp; &nbsp; &nbsp;Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."),
  items(
      icon: const Icon(Icons.access_alarm_sharp),
      title: "Interjection",
      dec:
          "<p><strong>Definition of Interjection:</strong> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p> <p>&nbsp; &nbsp; &nbsp;It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."),
  items(
      icon: const Icon(Icons.battery_alert),
      title: "About",
      dec:
          "<p><strong>Usage of About:</strong>&nbsp;English grammar is the way in which meanings are encoded into wordings in the English language.</p> <p>&nbsp; &nbsp; &nbsp;This includes the structure of words, phrases, clauses, and sentences, right up to the structure of whole texts.</p> <p><strong>What is Lorem Ipsum?</strong></p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p> <p><strong><img alt=\"To see images, Turn on internet Connection\" src=\"https://drive.google.com/uc?id=1cZIrXFPEjCcz3LQvih3leXF2nENg0uSd\" style=\"width: 100%; height: 250px;\" /></strong></p> <p><strong>Where does it come from?</strong></p> <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>"),
  items(
      icon: const Icon(Icons.help),
      title: "Help",
      dec:
          "<p><strong>Usage of About:</strong>&nbsp;English grammar is the way in which meanings are encoded into wordings in the English language.</p> <p>&nbsp; &nbsp; &nbsp;This includes the structure of words, phrases, clauses, and sentences, right up to the structure of whole texts.</p> <p><strong>What is Lorem Ipsum?</strong></p> <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p> <p><strong><img alt=\"To see images, Turn on internet Connection\" src=\"https://drive.google.com/uc?id=1cZIrXFPEjCcz3LQvih3leXF2nENg0uSd\" style=\"width: 100%; height: 250px;\" /></strong></p> <p><strong>Where does it come from?</strong></p> <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>")
];
